name: vendvibe
description: A new Flutter project for vending machine management.

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.6
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image: ^4.2.0
  flutter_image_compress: ^2.3.0

  cupertino_icons: ^1.0.6
  intl_phone_number_input: ^0.7.4
  url_launcher: ^6.3.0
  smooth_page_indicator: ^1.2.0+3
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/vv.jpg"   # Image for Android
  image_path_ios: "assets/vv.jpg"
